<?php
// namespace Fang;
require_once 'base.php';

/**
 * Provide methods to control user table (CRUD).
 * @author Fang
 */
class UserUtils
{
	// Cannot instantiation
	private function __construct($arg){}
	
	/**
	 * @param name 		name of new user
	 * @param sex 		sex of new user
	 * @return new user's ID (generated by AUTO_INCREAMENT)
	 */
	public function newUser($name,$sex){
		global $sql;
		// Id,name,phone,pwd,openId,AccessToken,RefreshToken,ACTexpires,position,sexual,type
		// $statement = $sql->prepare('INSERT INTO `user` VALUES(0,?,NULL,NULL,NULL,NULL,NULL,NULL,NULL,?,NULL)');
		$statement = $sql->prepare('INSERT INTO `user` VALUES(?,NULL,NULL,NULL,NULL,NULL,NULL,NULL,?,NULL)');
		$statement->bind_param($name,$sex);
		$statement->execute();

		return $sql->insert_id;
	}
	
	/**
	 * @param id 		id of user
	 * @param name 		new name
	 * @param sex 		new sex
	 * @return void
	 */
	public function updateNameSex($id,$name,$sex){
		global $sql;
		$statement = $sql->prepare('UPDATE `user` SET `name` = ?,`sexual` = ? WHERE `Id` = ?');
		$statement->bind_param($name,$sex,$id);
		$statement->execute();
	}

	/**
	 * @param id 		id of user
	 * @param name 		new location
	 * @return void
	 */
	public function updateLocation($id,$location){
		global $sql;
		$statement = $sql->prepare('UPDATE `user` SET `position` = ? WHERE `Id` = ?');
		$statement->bind_param($location,$id);
		$statement->execute();
	}

	/**
	 * @param id 		id of user
	 * @param tel 		new telephone number
	 * @return true for success, false for fail
	 */
	public function updateTel($id,$tel){
		global $sql;
		// Check phone number ...
		if (preg_match('/^1[3|4|5|8][0-9]\d{8}$/', $tel)){
			$statement = $sql->prepare('UPDATE `user` SET `phone` = ? WHERE `Id` = ?');
			$statement->bind_param($tel,$id);
			$statement->execute();
			return true;
		} else {
			return false;
		}
	}

	/**
	 * @param id 		id of user
	 * @return Array, 
	 	if 'success' is false, 'content' is errinfo; <br> 
	 	if 'success' is true, 'content' is Array (ASSOC).<br>
	 	fields: Id,name,phone,pwd,openId,AccessToken,RefreshToken,ACTexpires,position,sexual,type.
	 */
	public function getUserInfo($id){
		global $sql;
		$statement = $sql->prepare('SELECT * FROM `user` WHERE Id = ?');
		$statement->bind_param($id);
		$resultset = $statement->execute();
		$row = $resultset->fetch_assoc();
		if (count($row)!=1)
			return array('success' => false, 'content' => 'No such user!');
		else
			return array('success' => true, 'content' => $row);
	}

	/**
	 * @param id 		id of user
	 * @return Array, 
	 	if 'success' is false, 'content' is errinfo; <br> 
	 	if 'success' is true, 'content' is an array containing name,tel and sex.<br>
	 */
	public function getNameTelSex($id){
		global $sql;
		$statement = $sql->prepare('SELECT name,phone,sexual FROM `user` WHERE Id = ?');
		$statement->bind_param($id);
		$resultset = $statement->execute();
		$row = $resultset->fetch_assoc();
		if (count($row)!=1)
			return array('success' => false, 'content' => 'No such user!');
		else
			return array('success' => true, 'content' => array($row['name'],$row['phone'],$row['sexual']));
	}

	/**
	 * @param orderId 		id of order
	 * @return Array, 
	 	if 'success' is false, 'content' is errinfo; <br> 
	 	if 'success' is true, 'content' is publisher id.
	 */
	public function getPublisherByOrder($orderId){
		global $sql;
		$statement = $sql->prepare('SELECT userId FROM `orders` WHERE Id = ?');
		$statement->bind_param($orderId);
		$resultset = $statement->execute();
		$row = $resultset->fetch_assoc();
		if (count($row)!=1)
			return array('success' => false, 'content' => 'No such order!');
		else
			return array('success' => true, 'content' => $row['userId']);
	}

	/**
	 * @param orderId 		id of order
	 * @return Array, 
	 	if 'success' is false, 'content' is errinfo; <br> 
	 	if 'success' is true, 'content' is courier id.
	 */
	public function getCourierByOrder($orderId){
		global $sql;
		$statement = $sql->prepare('SELECT toker FROM `orders` WHERE Id = ?');
		$statement->bind_param($orderId);
		$resultset = $statement->execute();
		$row = $resultset->fetch_assoc();
		if (count($row)!=1)
			return array('success' => false, 'content' => 'No such order!');
		else
			return array('success' => true, 'content' => $row['toker']);
	}
}